site:
  name: 'Elvira Tüzép'
  site: 'https://elviratuzep.hu'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: dbBCJz4uzzW9sN1GGjjfmshoEAMUqCCRgkUNPuweXT0

# Default SEO metadata
metadata:
  title:
    default: "ElviraTüzép | Tartós Szerkezeti Fa és Minőségi Tüzelőanyag"
    template: ''
  description: 'Tartós fa, meleg otthon. Az Elvira Tüzép BSH gerendák, ragasztott faanyagok és minőségi brikettek forgalmazója. Fűtésre és építésre egy helyen.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: ElviraTüzép
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@onwidget'
    site: '@onwidget'
    cardType: summary_large_image

i18n:
  language: hu
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/tudastar/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'tudastar' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'tudastar/kategoria' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tudastar/tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: "G-9C27N57B3F" # or "G-XXXXXXXXXX"
      partytown: false

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
